[package]
name = "lapack-traits"
version = "0.2.2"
authors = ["Humberto Munoz Bauza <humberto.munozb@gmail.com>"]
edition = "2018"

description = "Generic real/complex scalar trait wrappers for BLAS and LAPACK routines"
keywords = ["algebra", "blas", "lapack", "complex"]
categories = ["mathematics", "science", "simulation"]

readme = "readme.md"
repository = "https://github.com/hmunozb/lapack-traits/"
license = "MIT"

[dependencies]
alga = {version="0.9"}
cblas = "0.2"
lapacke = "0.2.0"
num-complex = "0.2.3"
simba = {version="0.1", optional=true}

[dev-dependencies]
openblas-src = { version="0.7.0", default-features=false, features=["system"] }
lapacke-sys = "0.1.4"