[package]
name = "blas-traits"
version = "0.1.0"
authors = ["hmb <humberto.munozb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alga = "0.9.2"
cblas = "0.2"
lapacke = "0.2.0"
num-complex = "0.2.3"

[dev-dependencies]
openblas-src = { version="0.7.0", default-features=false, features=["system"] }
lapacke-sys = "0.1.4"